// Mocks generated by Mockito 5.4.2 from annotations
// in hakim_hub_mobile/test/features/hospital/data/repositories/hospital_detail_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hakim_hub_mobile/core/network/network_info.dart' as _i7;
import 'package:hakim_hub_mobile/features/hospital/data/datasources/hospital_detail_remote_datasource.dart'
    as _i3;
import 'package:hakim_hub_mobile/features/hospital/data/models/filter_doctors_model.dart'
    as _i6;
import 'package:hakim_hub_mobile/features/hospital/data/models/hospital_detail_model.dart'
    as _i2;
import 'package:hakim_hub_mobile/features/hospital/data/models/hospital_doctor_model.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInstitutionDetailModel_0 extends _i1.SmartFake
    implements _i2.InstitutionDetailModel {
  _FakeInstitutionDetailModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HospitalDetailRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHospitalDetailRemoteDataSource extends _i1.Mock
    implements _i3.HospitalDetailRemoteDataSource {
  MockHospitalDetailRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InstitutionDetailModel> getHospitalDetail(
          String? hospitalID) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHospitalDetail,
          [hospitalID],
        ),
        returnValue: _i4.Future<_i2.InstitutionDetailModel>.value(
            _FakeInstitutionDetailModel_0(
          this,
          Invocation.method(
            #getHospitalDetail,
            [hospitalID],
          ),
        )),
      ) as _i4.Future<_i2.InstitutionDetailModel>);
  @override
  _i4.Future<List<_i5.DoctorModel>> getDoctorByFilter(
          _i6.DoctorFilterModel? doctorFilterModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoctorByFilter,
          [doctorFilterModel],
        ),
        returnValue:
            _i4.Future<List<_i5.DoctorModel>>.value(<_i5.DoctorModel>[]),
      ) as _i4.Future<List<_i5.DoctorModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
