// Mocks generated by Mockito 5.4.2 from annotations
// in hakim_hub_mobile/test/features/chatbot/domain/repository/chat_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:hakim_hub_mobile/features/chatbot/domain/entities/chat_doctor_entity.dart'
    as _i3;
import 'package:hakim_hub_mobile/features/chatbot/domain/entities/chat_institute_entity.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChatInstituteEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatInstituteEntity extends _i1.Mock
    implements _i2.ChatInstituteEntity {
  MockChatInstituteEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get instituteName => (super.noSuchMethod(
        Invocation.getter(#instituteName),
        returnValue: '',
      ) as String);
  @override
  set instituteName(String? _instituteName) => super.noSuchMethod(
        Invocation.setter(
          #instituteName,
          _instituteName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i3.ChatDoctorEntity> get doctors => (super.noSuchMethod(
        Invocation.getter(#doctors),
        returnValue: <_i3.ChatDoctorEntity>[],
      ) as List<_i3.ChatDoctorEntity>);
  @override
  set doctors(List<_i3.ChatDoctorEntity>? _doctors) => super.noSuchMethod(
        Invocation.setter(
          #doctors,
          _doctors,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get instituteId => (super.noSuchMethod(
        Invocation.getter(#instituteId),
        returnValue: '',
      ) as String);
  @override
  set instituteId(String? _instituteId) => super.noSuchMethod(
        Invocation.setter(
          #instituteId,
          _instituteId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get logoUrl => (super.noSuchMethod(
        Invocation.getter(#logoUrl),
        returnValue: '',
      ) as String);
  @override
  set logoUrl(String? _logoUrl) => super.noSuchMethod(
        Invocation.setter(
          #logoUrl,
          _logoUrl,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}