// Mocks generated by Mockito 5.4.2 from annotations
// in hakim_hub_mobile/test/features/chatbot/domain/repository/chat_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hakim_hub_mobile/core/error/failures.dart' as _i5;
import 'package:hakim_hub_mobile/features/chatbot/domain/entities/chat_request_entity.dart'
    as _i7;
import 'package:hakim_hub_mobile/features/chatbot/domain/entities/chat_response_entity.dart'
    as _i6;
import 'package:hakim_hub_mobile/features/chatbot/domain/repositories/chat_repository.dart'
    as _i3;
import 'package:hakim_hub_mobile/features/chatbot/domain/usecases/get_chat_response.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatRepository_1 extends _i1.SmartFake
    implements _i3.ChatRepository {
  _FakeChatRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i3.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatResponse>> getChatResponse(
          _i7.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatResponse,
          [chatRequest],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ChatResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.ChatResponse>(
          this,
          Invocation.method(
            #getChatResponse,
            [chatRequest],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatResponse>>);
}

/// A class which mocks [GetChatResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChatResponse extends _i1.Mock implements _i8.GetChatResponse {
  MockGetChatResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChatRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeChatRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.ChatRepository);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatResponse>> call(
          _i7.ChatRequest? chatRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [chatRequest],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.ChatResponse>>.value(
                _FakeEither_0<_i5.Failure, _i6.ChatResponse>(
          this,
          Invocation.method(
            #call,
            [chatRequest],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatResponse>>);
}
