// Mocks generated by Mockito 5.4.2 from annotations
// in hakim_hub_mobile/test/features/hospital/presentation/bloc/hospital_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:hakim_hub_mobile/core/error/failures.dart' as _i6;
import 'package:hakim_hub_mobile/features/hospital/domain/entities/filter_doctor_domain.dart'
    as _i8;
import 'package:hakim_hub_mobile/features/hospital/domain/entities/hospital_detail_domain.dart'
    as _i10;
import 'package:hakim_hub_mobile/features/hospital/domain/entities/hospital_doctor_domain.dart'
    as _i7;
import 'package:hakim_hub_mobile/features/hospital/domain/repositories/hospital_detail_repository.dart'
    as _i2;
import 'package:hakim_hub_mobile/features/hospital/domain/usecases/get_doctor_by_filter.dart'
    as _i4;
import 'package:hakim_hub_mobile/features/hospital/domain/usecases/get_hospital_detail.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHospitalDetailRepository_0 extends _i1.SmartFake
    implements _i2.HospitalDetailRepository {
  _FakeHospitalDetailRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetDoctorByFilter].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDoctorByFilter extends _i1.Mock implements _i4.GetDoctorByFilter {
  MockGetDoctorByFilter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HospitalDetailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHospitalDetailRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HospitalDetailRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.DoctorDomain>>> call(
          _i8.DoctorFilterDomain? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.DoctorDomain>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.DoctorDomain>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.DoctorDomain>>>);
}

/// A class which mocks [GetHospitalDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHospitalDetail extends _i1.Mock implements _i9.GetHospitalDetail {
  MockGetHospitalDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HospitalDetailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHospitalDetailRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.HospitalDetailRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i10.InstitutionDetailDomain>> call(
          String? hospitalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [hospitalId],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i10.InstitutionDetailDomain>>.value(
            _FakeEither_1<_i6.Failure, _i10.InstitutionDetailDomain>(
          this,
          Invocation.method(
            #call,
            [hospitalId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i10.InstitutionDetailDomain>>);
}
